// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: hello.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HandlerHelloClient is the client API for HandlerHello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandlerHelloClient interface {
	Hello(ctx context.Context, in *HelloUser, opts ...grpc.CallOption) (*Blank, error)
}

type handlerHelloClient struct {
	cc grpc.ClientConnInterface
}

func NewHandlerHelloClient(cc grpc.ClientConnInterface) HandlerHelloClient {
	return &handlerHelloClient{cc}
}

func (c *handlerHelloClient) Hello(ctx context.Context, in *HelloUser, opts ...grpc.CallOption) (*Blank, error) {
	out := new(Blank)
	err := c.cc.Invoke(ctx, "/pb.HandlerHello/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandlerHelloServer is the server API for HandlerHello service.
// All implementations must embed UnimplementedHandlerHelloServer
// for forward compatibility
type HandlerHelloServer interface {
	Hello(context.Context, *HelloUser) (*Blank, error)
	mustEmbedUnimplementedHandlerHelloServer()
}

// UnimplementedHandlerHelloServer must be embedded to have forward compatible implementations.
type UnimplementedHandlerHelloServer struct {
}

func (UnimplementedHandlerHelloServer) Hello(context.Context, *HelloUser) (*Blank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHandlerHelloServer) mustEmbedUnimplementedHandlerHelloServer() {}

// UnsafeHandlerHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandlerHelloServer will
// result in compilation errors.
type UnsafeHandlerHelloServer interface {
	mustEmbedUnimplementedHandlerHelloServer()
}

func RegisterHandlerHelloServer(s grpc.ServiceRegistrar, srv HandlerHelloServer) {
	s.RegisterService(&HandlerHello_ServiceDesc, srv)
}

func _HandlerHello_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerHelloServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandlerHello/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerHelloServer).Hello(ctx, req.(*HelloUser))
	}
	return interceptor(ctx, in, info, handler)
}

// HandlerHello_ServiceDesc is the grpc.ServiceDesc for HandlerHello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandlerHello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HandlerHello",
	HandlerType: (*HandlerHelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HandlerHello_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
